# Generated by Django 4.0.6 on 2022-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=10)),
                ('productName', models.CharField(max_length=20)),
                ('productCost', models.IntegerField()),
                ('productImage', models.ImageField(upload_to=None)),
                ('productDescription', models.TextField()),
            ],
        ),
    ]
