# Generated by Django 4.0.6 on 2022-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='productImages'),
        ),
    ]
